# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-22 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_picture',
            field=models.ImageField(upload_to='df_goods'),
        ),
    ]
