# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('addressee', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
