# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='addressee',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='', max_length=40),
        ),
    ]
